[package]
name = "rust-surrealdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
surrealdb = "1.0.0-beta.9"
anyhow = "1.0"
grpc = "0.8.3"
protobuf = "3.2.0"
futures = "0.3.28"


[build-dependencies]
protoc-rust-grpc = "0.8.3"