run:
	
	go run main.go

compile:

	go build -o bin/main main.go

clean:

	rm -R bin

rmlog: 

	sudo rm -R ./logger/log

tidy:

	go mod tidy

.PHONY: run
.PHONY: tidy
.PHONY: compile
.PHONY: clean
.PHONY: sync